name: Update Stocks Data

on:
  schedule:
    # 12:00 ظهراً بتوقيت الإمارات (UTC+4) = 08:00 UTC يومياً
    - cron: "0 8 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas yfinance

      - name: Run scraper
        run: |
          python scrape_stocks.py --symbols DEWA SALIK NMDC --out public/stocks_data.json

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/stocks_data.json
          git commit -m "chore(data): auto-update stocks_data.json" || echo "No changes"
          git push
